<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb\Compare;

/**
 * Protobuf type <code>etcdserverpb.Compare.CompareResult</code>
 */
class CompareResult
{
    /**
     * Generated from protobuf enum <code>EQUAL = 0;</code>
     */
    const EQUAL = 0;
    /**
     * Generated from protobuf enum <code>GREATER = 1;</code>
     */
    const GREATER = 1;
    /**
     * Generated from protobuf enum <code>LESS = 2;</code>
     */
    const LESS = 2;
    /**
     * Generated from protobuf enum <code>NOT_EQUAL = 3;</code>
     */
    const NOT_EQUAL = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CompareResult::class, \Etcdserverpb\Compare_CompareResult::class);

