<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb\Compare;

/**
 * Protobuf type <code>etcdserverpb.Compare.CompareTarget</code>
 */
class CompareTarget
{
    /**
     * Generated from protobuf enum <code>VERSION = 0;</code>
     */
    const VERSION = 0;
    /**
     * Generated from protobuf enum <code>CREATE = 1;</code>
     */
    const CREATE = 1;
    /**
     * Generated from protobuf enum <code>MOD = 2;</code>
     */
    const MOD = 2;
    /**
     * Generated from protobuf enum <code>VALUE = 3;</code>
     */
    const VALUE = 3;
    /**
     * Generated from protobuf enum <code>LEASE = 4;</code>
     */
    const LEASE = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CompareTarget::class, \Etcdserverpb\Compare_CompareTarget::class);

