<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

namespace Mvccpb;

if (false) {
    /**
     * This class is deprecated. Use Mvccpb\Event\EventType instead.
     * @deprecated
     */
    class Event_EventType {}
}
class_exists(Event\EventType::class);
@trigger_error('Mvccpb\Event_EventType is deprecated and will be removed in the next major release. Use Mvccpb\Event\EventType instead', E_USER_DEPRECATED);

