<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

namespace Mvccpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mvccpb.KeyValue</code>
 */
class KeyValue extends \Google\Protobuf\Internal\Message
{
    /**
     * key is the key in bytes. An empty key is not allowed.
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * create_revision is the revision of last creation on this key.
     *
     * Generated from protobuf field <code>int64 create_revision = 2;</code>
     */
    private $create_revision = 0;
    /**
     * mod_revision is the revision of last modification on this key.
     *
     * Generated from protobuf field <code>int64 mod_revision = 3;</code>
     */
    private $mod_revision = 0;
    /**
     * version is the version of the key. A deletion resets
     * the version to zero and any modification of the key
     * increases its version.
     *
     * Generated from protobuf field <code>int64 version = 4;</code>
     */
    private $version = 0;
    /**
     * value is the value held by the key, in bytes.
     *
     * Generated from protobuf field <code>bytes value = 5;</code>
     */
    private $value = '';
    /**
     * lease is the ID of the lease that attached to key.
     * When the attached lease expires, the key will be deleted.
     * If lease is 0, then no lease is attached to the key.
     *
     * Generated from protobuf field <code>int64 lease = 6;</code>
     */
    private $lease = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *           key is the key in bytes. An empty key is not allowed.
     *     @type int|string $create_revision
     *           create_revision is the revision of last creation on this key.
     *     @type int|string $mod_revision
     *           mod_revision is the revision of last modification on this key.
     *     @type int|string $version
     *           version is the version of the key. A deletion resets
     *           the version to zero and any modification of the key
     *           increases its version.
     *     @type string $value
     *           value is the value held by the key, in bytes.
     *     @type int|string $lease
     *           lease is the ID of the lease that attached to key.
     *           When the attached lease expires, the key will be deleted.
     *           If lease is 0, then no lease is attached to the key.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kv::initOnce();
        parent::__construct($data);
    }

    /**
     * key is the key in bytes. An empty key is not allowed.
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * key is the key in bytes. An empty key is not allowed.
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * create_revision is the revision of last creation on this key.
     *
     * Generated from protobuf field <code>int64 create_revision = 2;</code>
     * @return int|string
     */
    public function getCreateRevision()
    {
        return $this->create_revision;
    }

    /**
     * create_revision is the revision of last creation on this key.
     *
     * Generated from protobuf field <code>int64 create_revision = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_revision = $var;

        return $this;
    }

    /**
     * mod_revision is the revision of last modification on this key.
     *
     * Generated from protobuf field <code>int64 mod_revision = 3;</code>
     * @return int|string
     */
    public function getModRevision()
    {
        return $this->mod_revision;
    }

    /**
     * mod_revision is the revision of last modification on this key.
     *
     * Generated from protobuf field <code>int64 mod_revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setModRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->mod_revision = $var;

        return $this;
    }

    /**
     * version is the version of the key. A deletion resets
     * the version to zero and any modification of the key
     * increases its version.
     *
     * Generated from protobuf field <code>int64 version = 4;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * version is the version of the key. A deletion resets
     * the version to zero and any modification of the key
     * increases its version.
     *
     * Generated from protobuf field <code>int64 version = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * value is the value held by the key, in bytes.
     *
     * Generated from protobuf field <code>bytes value = 5;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * value is the value held by the key, in bytes.
     *
     * Generated from protobuf field <code>bytes value = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * lease is the ID of the lease that attached to key.
     * When the attached lease expires, the key will be deleted.
     * If lease is 0, then no lease is attached to the key.
     *
     * Generated from protobuf field <code>int64 lease = 6;</code>
     * @return int|string
     */
    public function getLease()
    {
        return $this->lease;
    }

    /**
     * lease is the ID of the lease that attached to key.
     * When the attached lease expires, the key will be deleted.
     * If lease is 0, then no lease is attached to the key.
     *
     * Generated from protobuf field <code>int64 lease = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLease($var)
    {
        GPBUtil::checkInt64($var);
        $this->lease = $var;

        return $this;
    }

}

