<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

namespace Mvccpb\Event;

/**
 * Protobuf type <code>mvccpb.Event.EventType</code>
 */
class EventType
{
    /**
     * Generated from protobuf enum <code>PUT = 0;</code>
     */
    const PUT = 0;
    /**
     * Generated from protobuf enum <code>DELETE = 1;</code>
     */
    const DELETE = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EventType::class, \Mvccpb\Event_EventType::class);

