<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a020a0a617574682e70726f746f120661757468706222350a04557365" .
            "72120c0a046e616d6518012001280c12100a0870617373776f7264180220" .
            "01280c120d0a05726f6c65731803200328092283010a0a5065726d697373" .
            "696f6e12290a087065726d5479706518012001280e32172e617574687062" .
            "2e5065726d697373696f6e2e54797065120b0a036b657918022001280c12" .
            "110a0972616e67655f656e6418032001280c222a0a045479706512080a04" .
            "52454144100012090a0557524954451001120d0a09524541445752495445" .
            "1002223f0a04526f6c65120c0a046e616d6518012001280c12290a0d6b65" .
            "795065726d697373696f6e18022003280b32122e6175746870622e506572" .
            "6d697373696f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

