<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

namespace GPBMetadata;

class Kv
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5020a086b762e70726f746f12066d766363706222750a084b65795661" .
            "6c7565120b0a036b657918012001280c12170a0f6372656174655f726576" .
            "6973696f6e18022001280312140a0c6d6f645f7265766973696f6e180320" .
            "012803120f0a0776657273696f6e180420012803120d0a0576616c756518" .
            "052001280c120d0a056c656173651806200128032291010a054576656e74" .
            "12250a047479706518012001280e32172e6d76636370622e4576656e742e" .
            "4576656e7454797065121c0a026b7618022001280b32102e6d7663637062" .
            "2e4b657956616c756512210a07707265765f6b7618032001280b32102e6d" .
            "76636370622e4b657956616c756522200a094576656e745479706512070a" .
            "035055541000120a0a0644454c4554451001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

