<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb\WatchCreateRequest;

/**
 * Protobuf type <code>etcdserverpb.WatchCreateRequest.FilterType</code>
 */
class FilterType
{
    /**
     * filter out put event.
     *
     * Generated from protobuf enum <code>NOPUT = 0;</code>
     */
    const NOPUT = 0;
    /**
     * filter out delete event.
     *
     * Generated from protobuf enum <code>NODELETE = 1;</code>
     */
    const NODELETE = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FilterType::class, \Etcdserverpb\WatchCreateRequest_FilterType::class);

