<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb\RangeRequest;

/**
 * Protobuf type <code>etcdserverpb.RangeRequest.SortOrder</code>
 */
class SortOrder
{
    /**
     * default, no sorting
     *
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * lowest target value first
     *
     * Generated from protobuf enum <code>ASCEND = 1;</code>
     */
    const ASCEND = 1;
    /**
     * highest target value first
     *
     * Generated from protobuf enum <code>DESCEND = 2;</code>
     */
    const DESCEND = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SortOrder::class, \Etcdserverpb\RangeRequest_SortOrder::class);

