<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca010a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c64222a0a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "012809120c0a0461646472180220012809222b0a0a48656c6c6f5265706c" .
            "79120f0a076d657373616765180120012809120c0a046461746118022001" .
            "280932490a0747726565746572123e0a0853617948656c6c6f12182e6865" .
            "6c6c6f776f726c642e48656c6c6f526571756573741a162e68656c6c6f77" .
            "6f726c642e48656c6c6f5265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

