<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

/**
 * Protobuf type <code>etcdserverpb.AlarmType</code>
 */
class AlarmType
{
    /**
     * default, used to query if any alarm is active
     *
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * space quota is exhausted
     *
     * Generated from protobuf enum <code>NOSPACE = 1;</code>
     */
    const NOSPACE = 1;
    /**
     * kv store corruption detected
     *
     * Generated from protobuf enum <code>CORRUPT = 2;</code>
     */
    const CORRUPT = 2;
}

