<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

if (false) {
    /**
     * This class is deprecated. Use Etcdserverpb\AlarmRequest\AlarmAction instead.
     * @deprecated
     */
    class AlarmRequest_AlarmAction {}
}
class_exists(AlarmRequest\AlarmAction::class);
@trigger_error('Etcdserverpb\AlarmRequest_AlarmAction is deprecated and will be removed in the next major release. Use Etcdserverpb\AlarmRequest\AlarmAction instead', E_USER_DEPRECATED);

