<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.AlarmResponse</code>
 */
class AlarmResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * alarms is a list of alarms associated with the alarm request.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     */
    private $alarms;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\ResponseHeader $header
     *     @type \Etcdserverpb\AlarmMember[]|\Google\Protobuf\Internal\RepeatedField $alarms
     *           alarms is a list of alarms associated with the alarm request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcdserverpb\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcdserverpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * alarms is a list of alarms associated with the alarm request.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAlarms()
    {
        return $this->alarms;
    }

    /**
     * alarms is a list of alarms associated with the alarm request.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     * @param \Etcdserverpb\AlarmMember[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAlarms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcdserverpb\AlarmMember::class);
        $this->alarms = $arr;

        return $this;
    }

}

