<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.AlarmRequest</code>
 */
class AlarmRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * action is the kind of alarm request to issue. The action
     * may GET alarm statuses, ACTIVATE an alarm, or DEACTIVATE a
     * raised alarm.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmRequest.AlarmAction action = 1;</code>
     */
    private $action = 0;
    /**
     * memberID is the ID of the member associated with the alarm. If memberID is 0, the
     * alarm request covers all members.
     *
     * Generated from protobuf field <code>uint64 memberID = 2;</code>
     */
    private $memberID = 0;
    /**
     * alarm is the type of alarm to consider for this request.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmType alarm = 3;</code>
     */
    private $alarm = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action
     *           action is the kind of alarm request to issue. The action
     *           may GET alarm statuses, ACTIVATE an alarm, or DEACTIVATE a
     *           raised alarm.
     *     @type int|string $memberID
     *           memberID is the ID of the member associated with the alarm. If memberID is 0, the
     *           alarm request covers all members.
     *     @type int $alarm
     *           alarm is the type of alarm to consider for this request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * action is the kind of alarm request to issue. The action
     * may GET alarm statuses, ACTIVATE an alarm, or DEACTIVATE a
     * raised alarm.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmRequest.AlarmAction action = 1;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * action is the kind of alarm request to issue. The action
     * may GET alarm statuses, ACTIVATE an alarm, or DEACTIVATE a
     * raised alarm.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmRequest.AlarmAction action = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Etcdserverpb\AlarmRequest_AlarmAction::class);
        $this->action = $var;

        return $this;
    }

    /**
     * memberID is the ID of the member associated with the alarm. If memberID is 0, the
     * alarm request covers all members.
     *
     * Generated from protobuf field <code>uint64 memberID = 2;</code>
     * @return int|string
     */
    public function getMemberID()
    {
        return $this->memberID;
    }

    /**
     * memberID is the ID of the member associated with the alarm. If memberID is 0, the
     * alarm request covers all members.
     *
     * Generated from protobuf field <code>uint64 memberID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemberID($var)
    {
        GPBUtil::checkUint64($var);
        $this->memberID = $var;

        return $this;
    }

    /**
     * alarm is the type of alarm to consider for this request.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmType alarm = 3;</code>
     * @return int
     */
    public function getAlarm()
    {
        return $this->alarm;
    }

    /**
     * alarm is the type of alarm to consider for this request.
     *
     * Generated from protobuf field <code>.etcdserverpb.AlarmType alarm = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAlarm($var)
    {
        GPBUtil::checkEnum($var, \Etcdserverpb\AlarmType::class);
        $this->alarm = $var;

        return $this;
    }

}

