<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.AuthUserGrantRoleRequest</code>
 */
class AuthUserGrantRoleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * user is the name of the user which should be granted a given role.
     *
     * Generated from protobuf field <code>string user = 1;</code>
     */
    private $user = '';
    /**
     * role is the name of the role to grant to the user.
     *
     * Generated from protobuf field <code>string role = 2;</code>
     */
    private $role = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user
     *           user is the name of the user which should be granted a given role.
     *     @type string $role
     *           role is the name of the role to grant to the user.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * user is the name of the user which should be granted a given role.
     *
     * Generated from protobuf field <code>string user = 1;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * user is the name of the user which should be granted a given role.
     *
     * Generated from protobuf field <code>string user = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * role is the name of the role to grant to the user.
     *
     * Generated from protobuf field <code>string role = 2;</code>
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * role is the name of the role to grant to the user.
     *
     * Generated from protobuf field <code>string role = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;

        return $this;
    }

}

