<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.AuthRoleGrantPermissionRequest</code>
 */
class AuthRoleGrantPermissionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * name is the name of the role which will be granted the permission.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * perm is the permission to grant to the role.
     *
     * Generated from protobuf field <code>.authpb.Permission perm = 2;</code>
     */
    private $perm = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           name is the name of the role which will be granted the permission.
     *     @type \Authpb\Permission $perm
     *           perm is the permission to grant to the role.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * name is the name of the role which will be granted the permission.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name is the name of the role which will be granted the permission.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * perm is the permission to grant to the role.
     *
     * Generated from protobuf field <code>.authpb.Permission perm = 2;</code>
     * @return \Authpb\Permission
     */
    public function getPerm()
    {
        return $this->perm;
    }

    /**
     * perm is the permission to grant to the role.
     *
     * Generated from protobuf field <code>.authpb.Permission perm = 2;</code>
     * @param \Authpb\Permission $var
     * @return $this
     */
    public function setPerm($var)
    {
        GPBUtil::checkMessage($var, \Authpb\Permission::class);
        $this->perm = $var;

        return $this;
    }

}

