<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

if (false) {
    /**
     * This class is deprecated. Use Etcdserverpb\Compare\CompareTarget instead.
     * @deprecated
     */
    class Compare_CompareTarget {}
}
class_exists(Compare\CompareTarget::class);
@trigger_error('Etcdserverpb\Compare_CompareTarget is deprecated and will be removed in the next major release. Use Etcdserverpb\Compare\CompareTarget instead', E_USER_DEPRECATED);

