<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CompactionRequest compacts the key-value store up to a given revision. All superseded keys
 * with a revision less than the compaction revision will be removed.
 *
 * Generated from protobuf message <code>etcdserverpb.CompactionRequest</code>
 */
class CompactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * revision is the key-value store revision for the compaction operation.
     *
     * Generated from protobuf field <code>int64 revision = 1;</code>
     */
    private $revision = 0;
    /**
     * physical is set so the RPC will wait until the compaction is physically
     * applied to the local database such that compacted entries are totally
     * removed from the backend database.
     *
     * Generated from protobuf field <code>bool physical = 2;</code>
     */
    private $physical = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $revision
     *           revision is the key-value store revision for the compaction operation.
     *     @type bool $physical
     *           physical is set so the RPC will wait until the compaction is physically
     *           applied to the local database such that compacted entries are totally
     *           removed from the backend database.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * revision is the key-value store revision for the compaction operation.
     *
     * Generated from protobuf field <code>int64 revision = 1;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * revision is the key-value store revision for the compaction operation.
     *
     * Generated from protobuf field <code>int64 revision = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * physical is set so the RPC will wait until the compaction is physically
     * applied to the local database such that compacted entries are totally
     * removed from the backend database.
     *
     * Generated from protobuf field <code>bool physical = 2;</code>
     * @return bool
     */
    public function getPhysical()
    {
        return $this->physical;
    }

    /**
     * physical is set so the RPC will wait until the compaction is physically
     * applied to the local database such that compacted entries are totally
     * removed from the backend database.
     *
     * Generated from protobuf field <code>bool physical = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setPhysical($var)
    {
        GPBUtil::checkBool($var);
        $this->physical = $var;

        return $this;
    }

}

