<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

if (false) {
    /**
     * This class is deprecated. Use Etcdserverpb\Compare\CompareResult instead.
     * @deprecated
     */
    class Compare_CompareResult {}
}
class_exists(Compare\CompareResult::class);
@trigger_error('Etcdserverpb\Compare_CompareResult is deprecated and will be removed in the next major release. Use Etcdserverpb\Compare\CompareResult instead', E_USER_DEPRECATED);

