<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.DeleteRangeResponse</code>
 */
class DeleteRangeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * deleted is the number of keys deleted by the delete range request.
     *
     * Generated from protobuf field <code>int64 deleted = 2;</code>
     */
    private $deleted = 0;
    /**
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
     */
    private $prev_kvs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\ResponseHeader $header
     *     @type int|string $deleted
     *           deleted is the number of keys deleted by the delete range request.
     *     @type \Mvccpb\KeyValue[]|\Google\Protobuf\Internal\RepeatedField $prev_kvs
     *           if prev_kv is set in the request, the previous key-value pairs will be returned.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcdserverpb\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcdserverpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * deleted is the number of keys deleted by the delete range request.
     *
     * Generated from protobuf field <code>int64 deleted = 2;</code>
     * @return int|string
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * deleted is the number of keys deleted by the delete range request.
     *
     * Generated from protobuf field <code>int64 deleted = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrevKvs()
    {
        return $this->prev_kvs;
    }

    /**
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
     * @param \Mvccpb\KeyValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrevKvs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mvccpb\KeyValue::class);
        $this->prev_kvs = $arr;

        return $this;
    }

}

