<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.LeaseLeasesResponse</code>
 */
class LeaseLeasesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseStatus leases = 2;</code>
     */
    private $leases;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\ResponseHeader $header
     *     @type \Etcdserverpb\LeaseStatus[]|\Google\Protobuf\Internal\RepeatedField $leases
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcdserverpb\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcdserverpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseStatus leases = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLeases()
    {
        return $this->leases;
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseStatus leases = 2;</code>
     * @param \Etcdserverpb\LeaseStatus[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLeases($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcdserverpb\LeaseStatus::class);
        $this->leases = $arr;

        return $this;
    }

}

