<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.LeaseTimeToLiveResponse</code>
 */
class LeaseTimeToLiveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * ID is the lease ID from the keep alive request.
     *
     * Generated from protobuf field <code>int64 ID = 2;</code>
     */
    private $ID = 0;
    /**
     * TTL is the remaining TTL in seconds for the lease; the lease will expire in under TTL+1 seconds.
     *
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     */
    private $TTL = 0;
    /**
     * GrantedTTL is the initial granted time in seconds upon lease creation/renewal.
     *
     * Generated from protobuf field <code>int64 grantedTTL = 4;</code>
     */
    private $grantedTTL = 0;
    /**
     * Keys is the list of keys attached to this lease.
     *
     * Generated from protobuf field <code>repeated bytes keys = 5;</code>
     */
    private $keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\ResponseHeader $header
     *     @type int|string $ID
     *           ID is the lease ID from the keep alive request.
     *     @type int|string $TTL
     *           TTL is the remaining TTL in seconds for the lease; the lease will expire in under TTL+1 seconds.
     *     @type int|string $grantedTTL
     *           GrantedTTL is the initial granted time in seconds upon lease creation/renewal.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $keys
     *           Keys is the list of keys attached to this lease.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcdserverpb\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcdserverpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * ID is the lease ID from the keep alive request.
     *
     * Generated from protobuf field <code>int64 ID = 2;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * ID is the lease ID from the keep alive request.
     *
     * Generated from protobuf field <code>int64 ID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * TTL is the remaining TTL in seconds for the lease; the lease will expire in under TTL+1 seconds.
     *
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @return int|string
     */
    public function getTTL()
    {
        return $this->TTL;
    }

    /**
     * TTL is the remaining TTL in seconds for the lease; the lease will expire in under TTL+1 seconds.
     *
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTTL($var)
    {
        GPBUtil::checkInt64($var);
        $this->TTL = $var;

        return $this;
    }

    /**
     * GrantedTTL is the initial granted time in seconds upon lease creation/renewal.
     *
     * Generated from protobuf field <code>int64 grantedTTL = 4;</code>
     * @return int|string
     */
    public function getGrantedTTL()
    {
        return $this->grantedTTL;
    }

    /**
     * GrantedTTL is the initial granted time in seconds upon lease creation/renewal.
     *
     * Generated from protobuf field <code>int64 grantedTTL = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGrantedTTL($var)
    {
        GPBUtil::checkInt64($var);
        $this->grantedTTL = $var;

        return $this;
    }

    /**
     * Keys is the list of keys attached to this lease.
     *
     * Generated from protobuf field <code>repeated bytes keys = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Keys is the list of keys attached to this lease.
     *
     * Generated from protobuf field <code>repeated bytes keys = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->keys = $arr;

        return $this;
    }

}

