<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.LeaseCheckpointRequest</code>
 */
class LeaseCheckpointRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseCheckpoint checkpoints = 1;</code>
     */
    private $checkpoints;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\LeaseCheckpoint[]|\Google\Protobuf\Internal\RepeatedField $checkpoints
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseCheckpoint checkpoints = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCheckpoints()
    {
        return $this->checkpoints;
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.LeaseCheckpoint checkpoints = 1;</code>
     * @param \Etcdserverpb\LeaseCheckpoint[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCheckpoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcdserverpb\LeaseCheckpoint::class);
        $this->checkpoints = $arr;

        return $this;
    }

}

