<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.MemberAddRequest</code>
 */
class MemberAddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     *
     * Generated from protobuf field <code>repeated string peerURLs = 1;</code>
     */
    private $peerURLs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $peerURLs
     *           peerURLs is the list of URLs the added member will use to communicate with the cluster.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     *
     * Generated from protobuf field <code>repeated string peerURLs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeerURLs()
    {
        return $this->peerURLs;
    }

    /**
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     *
     * Generated from protobuf field <code>repeated string peerURLs = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeerURLs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->peerURLs = $arr;

        return $this;
    }

}

