<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.MemberRemoveRequest</code>
 */
class MemberRemoveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * ID is the member ID of the member to remove.
     *
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     */
    private $ID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ID
     *           ID is the member ID of the member to remove.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * ID is the member ID of the member to remove.
     *
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * ID is the member ID of the member to remove.
     *
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkUint64($var);
        $this->ID = $var;

        return $this;
    }

}

