<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.MoveLeaderRequest</code>
 */
class MoveLeaderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * targetID is the node ID for the new leader.
     *
     * Generated from protobuf field <code>uint64 targetID = 1;</code>
     */
    private $targetID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $targetID
     *           targetID is the node ID for the new leader.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * targetID is the node ID for the new leader.
     *
     * Generated from protobuf field <code>uint64 targetID = 1;</code>
     * @return int|string
     */
    public function getTargetID()
    {
        return $this->targetID;
    }

    /**
     * targetID is the node ID for the new leader.
     *
     * Generated from protobuf field <code>uint64 targetID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetID($var)
    {
        GPBUtil::checkUint64($var);
        $this->targetID = $var;

        return $this;
    }

}

