<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.RangeRequest</code>
 */
class RangeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * key is the first key for the range. If range_end is not given, the request only looks up key.
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * range_end is the upper bound on the requested range [key, range_end).
     * If range_end is '\0', the range is all keys >= key.
     * If range_end is key plus one (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"),
     * then the range request gets all keys prefixed with key.
     * If both key and range_end are '\0', then the range request returns all keys.
     *
     * Generated from protobuf field <code>bytes range_end = 2;</code>
     */
    private $range_end = '';
    /**
     * limit is a limit on the number of keys returned for the request. When limit is set to 0,
     * it is treated as no limit.
     *
     * Generated from protobuf field <code>int64 limit = 3;</code>
     */
    private $limit = 0;
    /**
     * revision is the point-in-time of the key-value store to use for the range.
     * If revision is less or equal to zero, the range is over the newest key-value store.
     * If the revision has been compacted, ErrCompacted is returned as a response.
     *
     * Generated from protobuf field <code>int64 revision = 4;</code>
     */
    private $revision = 0;
    /**
     * sort_order is the order for returned sorted results.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest.SortOrder sort_order = 5;</code>
     */
    private $sort_order = 0;
    /**
     * sort_target is the key-value field to use for sorting.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest.SortTarget sort_target = 6;</code>
     */
    private $sort_target = 0;
    /**
     * serializable sets the range request to use serializable member-local reads.
     * Range requests are linearizable by default; linearizable requests have higher
     * latency and lower throughput than serializable requests but reflect the current
     * consensus of the cluster. For better performance, in exchange for possible stale reads,
     * a serializable range request is served locally without needing to reach consensus
     * with other nodes in the cluster.
     *
     * Generated from protobuf field <code>bool serializable = 7;</code>
     */
    private $serializable = false;
    /**
     * keys_only when set returns only the keys and not the values.
     *
     * Generated from protobuf field <code>bool keys_only = 8;</code>
     */
    private $keys_only = false;
    /**
     * count_only when set returns only the count of the keys in the range.
     *
     * Generated from protobuf field <code>bool count_only = 9;</code>
     */
    private $count_only = false;
    /**
     * min_mod_revision is the lower bound for returned key mod revisions; all keys with
     * lesser mod revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 min_mod_revision = 10;</code>
     */
    private $min_mod_revision = 0;
    /**
     * max_mod_revision is the upper bound for returned key mod revisions; all keys with
     * greater mod revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 max_mod_revision = 11;</code>
     */
    private $max_mod_revision = 0;
    /**
     * min_create_revision is the lower bound for returned key create revisions; all keys with
     * lesser create revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 min_create_revision = 12;</code>
     */
    private $min_create_revision = 0;
    /**
     * max_create_revision is the upper bound for returned key create revisions; all keys with
     * greater create revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 max_create_revision = 13;</code>
     */
    private $max_create_revision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *           key is the first key for the range. If range_end is not given, the request only looks up key.
     *     @type string $range_end
     *           range_end is the upper bound on the requested range [key, range_end).
     *           If range_end is '\0', the range is all keys >= key.
     *           If range_end is key plus one (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"),
     *           then the range request gets all keys prefixed with key.
     *           If both key and range_end are '\0', then the range request returns all keys.
     *     @type int|string $limit
     *           limit is a limit on the number of keys returned for the request. When limit is set to 0,
     *           it is treated as no limit.
     *     @type int|string $revision
     *           revision is the point-in-time of the key-value store to use for the range.
     *           If revision is less or equal to zero, the range is over the newest key-value store.
     *           If the revision has been compacted, ErrCompacted is returned as a response.
     *     @type int $sort_order
     *           sort_order is the order for returned sorted results.
     *     @type int $sort_target
     *           sort_target is the key-value field to use for sorting.
     *     @type bool $serializable
     *           serializable sets the range request to use serializable member-local reads.
     *           Range requests are linearizable by default; linearizable requests have higher
     *           latency and lower throughput than serializable requests but reflect the current
     *           consensus of the cluster. For better performance, in exchange for possible stale reads,
     *           a serializable range request is served locally without needing to reach consensus
     *           with other nodes in the cluster.
     *     @type bool $keys_only
     *           keys_only when set returns only the keys and not the values.
     *     @type bool $count_only
     *           count_only when set returns only the count of the keys in the range.
     *     @type int|string $min_mod_revision
     *           min_mod_revision is the lower bound for returned key mod revisions; all keys with
     *           lesser mod revisions will be filtered away.
     *     @type int|string $max_mod_revision
     *           max_mod_revision is the upper bound for returned key mod revisions; all keys with
     *           greater mod revisions will be filtered away.
     *     @type int|string $min_create_revision
     *           min_create_revision is the lower bound for returned key create revisions; all keys with
     *           lesser create revisions will be filtered away.
     *     @type int|string $max_create_revision
     *           max_create_revision is the upper bound for returned key create revisions; all keys with
     *           greater create revisions will be filtered away.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * key is the first key for the range. If range_end is not given, the request only looks up key.
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * key is the first key for the range. If range_end is not given, the request only looks up key.
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * range_end is the upper bound on the requested range [key, range_end).
     * If range_end is '\0', the range is all keys >= key.
     * If range_end is key plus one (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"),
     * then the range request gets all keys prefixed with key.
     * If both key and range_end are '\0', then the range request returns all keys.
     *
     * Generated from protobuf field <code>bytes range_end = 2;</code>
     * @return string
     */
    public function getRangeEnd()
    {
        return $this->range_end;
    }

    /**
     * range_end is the upper bound on the requested range [key, range_end).
     * If range_end is '\0', the range is all keys >= key.
     * If range_end is key plus one (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"),
     * then the range request gets all keys prefixed with key.
     * If both key and range_end are '\0', then the range request returns all keys.
     *
     * Generated from protobuf field <code>bytes range_end = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRangeEnd($var)
    {
        GPBUtil::checkString($var, False);
        $this->range_end = $var;

        return $this;
    }

    /**
     * limit is a limit on the number of keys returned for the request. When limit is set to 0,
     * it is treated as no limit.
     *
     * Generated from protobuf field <code>int64 limit = 3;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * limit is a limit on the number of keys returned for the request. When limit is set to 0,
     * it is treated as no limit.
     *
     * Generated from protobuf field <code>int64 limit = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * revision is the point-in-time of the key-value store to use for the range.
     * If revision is less or equal to zero, the range is over the newest key-value store.
     * If the revision has been compacted, ErrCompacted is returned as a response.
     *
     * Generated from protobuf field <code>int64 revision = 4;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * revision is the point-in-time of the key-value store to use for the range.
     * If revision is less or equal to zero, the range is over the newest key-value store.
     * If the revision has been compacted, ErrCompacted is returned as a response.
     *
     * Generated from protobuf field <code>int64 revision = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * sort_order is the order for returned sorted results.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest.SortOrder sort_order = 5;</code>
     * @return int
     */
    public function getSortOrder()
    {
        return $this->sort_order;
    }

    /**
     * sort_order is the order for returned sorted results.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest.SortOrder sort_order = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSortOrder($var)
    {
        GPBUtil::checkEnum($var, \Etcdserverpb\RangeRequest_SortOrder::class);
        $this->sort_order = $var;

        return $this;
    }

    /**
     * sort_target is the key-value field to use for sorting.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest.SortTarget sort_target = 6;</code>
     * @return int
     */
    public function getSortTarget()
    {
        return $this->sort_target;
    }

    /**
     * sort_target is the key-value field to use for sorting.
     *
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest.SortTarget sort_target = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSortTarget($var)
    {
        GPBUtil::checkEnum($var, \Etcdserverpb\RangeRequest_SortTarget::class);
        $this->sort_target = $var;

        return $this;
    }

    /**
     * serializable sets the range request to use serializable member-local reads.
     * Range requests are linearizable by default; linearizable requests have higher
     * latency and lower throughput than serializable requests but reflect the current
     * consensus of the cluster. For better performance, in exchange for possible stale reads,
     * a serializable range request is served locally without needing to reach consensus
     * with other nodes in the cluster.
     *
     * Generated from protobuf field <code>bool serializable = 7;</code>
     * @return bool
     */
    public function getSerializable()
    {
        return $this->serializable;
    }

    /**
     * serializable sets the range request to use serializable member-local reads.
     * Range requests are linearizable by default; linearizable requests have higher
     * latency and lower throughput than serializable requests but reflect the current
     * consensus of the cluster. For better performance, in exchange for possible stale reads,
     * a serializable range request is served locally without needing to reach consensus
     * with other nodes in the cluster.
     *
     * Generated from protobuf field <code>bool serializable = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setSerializable($var)
    {
        GPBUtil::checkBool($var);
        $this->serializable = $var;

        return $this;
    }

    /**
     * keys_only when set returns only the keys and not the values.
     *
     * Generated from protobuf field <code>bool keys_only = 8;</code>
     * @return bool
     */
    public function getKeysOnly()
    {
        return $this->keys_only;
    }

    /**
     * keys_only when set returns only the keys and not the values.
     *
     * Generated from protobuf field <code>bool keys_only = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setKeysOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->keys_only = $var;

        return $this;
    }

    /**
     * count_only when set returns only the count of the keys in the range.
     *
     * Generated from protobuf field <code>bool count_only = 9;</code>
     * @return bool
     */
    public function getCountOnly()
    {
        return $this->count_only;
    }

    /**
     * count_only when set returns only the count of the keys in the range.
     *
     * Generated from protobuf field <code>bool count_only = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setCountOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->count_only = $var;

        return $this;
    }

    /**
     * min_mod_revision is the lower bound for returned key mod revisions; all keys with
     * lesser mod revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 min_mod_revision = 10;</code>
     * @return int|string
     */
    public function getMinModRevision()
    {
        return $this->min_mod_revision;
    }

    /**
     * min_mod_revision is the lower bound for returned key mod revisions; all keys with
     * lesser mod revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 min_mod_revision = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinModRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_mod_revision = $var;

        return $this;
    }

    /**
     * max_mod_revision is the upper bound for returned key mod revisions; all keys with
     * greater mod revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 max_mod_revision = 11;</code>
     * @return int|string
     */
    public function getMaxModRevision()
    {
        return $this->max_mod_revision;
    }

    /**
     * max_mod_revision is the upper bound for returned key mod revisions; all keys with
     * greater mod revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 max_mod_revision = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxModRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_mod_revision = $var;

        return $this;
    }

    /**
     * min_create_revision is the lower bound for returned key create revisions; all keys with
     * lesser create revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 min_create_revision = 12;</code>
     * @return int|string
     */
    public function getMinCreateRevision()
    {
        return $this->min_create_revision;
    }

    /**
     * min_create_revision is the lower bound for returned key create revisions; all keys with
     * lesser create revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 min_create_revision = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinCreateRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_create_revision = $var;

        return $this;
    }

    /**
     * max_create_revision is the upper bound for returned key create revisions; all keys with
     * greater create revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 max_create_revision = 13;</code>
     * @return int|string
     */
    public function getMaxCreateRevision()
    {
        return $this->max_create_revision;
    }

    /**
     * max_create_revision is the upper bound for returned key create revisions; all keys with
     * greater create revisions will be filtered away.
     *
     * Generated from protobuf field <code>int64 max_create_revision = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxCreateRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_create_revision = $var;

        return $this;
    }

}

