<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

if (false) {
    /**
     * This class is deprecated. Use Etcdserverpb\RangeRequest\SortOrder instead.
     * @deprecated
     */
    class RangeRequest_SortOrder {}
}
class_exists(RangeRequest\SortOrder::class);
@trigger_error('Etcdserverpb\RangeRequest_SortOrder is deprecated and will be removed in the next major release. Use Etcdserverpb\RangeRequest\SortOrder instead', E_USER_DEPRECATED);

