<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.RangeResponse</code>
 */
class RangeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     */
    private $kvs;
    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     */
    private $more = false;
    /**
     * count is set to the number of keys within the range when requested.
     *
     * Generated from protobuf field <code>int64 count = 4;</code>
     */
    private $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\ResponseHeader $header
     *     @type \Mvccpb\KeyValue[]|\Google\Protobuf\Internal\RepeatedField $kvs
     *           kvs is the list of key-value pairs matched by the range request.
     *           kvs is empty when count is requested.
     *     @type bool $more
     *           more indicates if there are more keys to return in the requested range.
     *     @type int|string $count
     *           count is set to the number of keys within the range when requested.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcdserverpb\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcdserverpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKvs()
    {
        return $this->kvs;
    }

    /**
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     *
     * Generated from protobuf field <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     * @param \Mvccpb\KeyValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKvs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mvccpb\KeyValue::class);
        $this->kvs = $arr;

        return $this;
    }

    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     * @return bool
     */
    public function getMore()
    {
        return $this->more;
    }

    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMore($var)
    {
        GPBUtil::checkBool($var);
        $this->more = $var;

        return $this;
    }

    /**
     * count is set to the number of keys within the range when requested.
     *
     * Generated from protobuf field <code>int64 count = 4;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * count is set to the number of keys within the range when requested.
     *
     * Generated from protobuf field <code>int64 count = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

}

