<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

if (false) {
    /**
     * This class is deprecated. Use Etcdserverpb\RangeRequest\SortTarget instead.
     * @deprecated
     */
    class RangeRequest_SortTarget {}
}
class_exists(RangeRequest\SortTarget::class);
@trigger_error('Etcdserverpb\RangeRequest_SortTarget is deprecated and will be removed in the next major release. Use Etcdserverpb\RangeRequest\SortTarget instead', E_USER_DEPRECATED);

