<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.RequestOp</code>
 */
class RequestOp extends \Google\Protobuf\Internal\Message
{
    protected $request;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\RangeRequest $request_range
     *     @type \Etcdserverpb\PutRequest $request_put
     *     @type \Etcdserverpb\DeleteRangeRequest $request_delete_range
     *     @type \Etcdserverpb\TxnRequest $request_txn
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     * @return \Etcdserverpb\RangeRequest
     */
    public function getRequestRange()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     * @param \Etcdserverpb\RangeRequest $var
     * @return $this
     */
    public function setRequestRange($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\RangeRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutRequest request_put = 2;</code>
     * @return \Etcdserverpb\PutRequest
     */
    public function getRequestPut()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutRequest request_put = 2;</code>
     * @param \Etcdserverpb\PutRequest $var
     * @return $this
     */
    public function setRequestPut($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\PutRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     * @return \Etcdserverpb\DeleteRangeRequest
     */
    public function getRequestDeleteRange()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     * @param \Etcdserverpb\DeleteRangeRequest $var
     * @return $this
     */
    public function setRequestDeleteRange($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\DeleteRangeRequest::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.TxnRequest request_txn = 4;</code>
     * @return \Etcdserverpb\TxnRequest
     */
    public function getRequestTxn()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.TxnRequest request_txn = 4;</code>
     * @param \Etcdserverpb\TxnRequest $var
     * @return $this
     */
    public function setRequestTxn($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\TxnRequest::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

