<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.ResponseHeader</code>
 */
class ResponseHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * cluster_id is the ID of the cluster which sent the response.
     *
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     */
    private $cluster_id = 0;
    /**
     * member_id is the ID of the member which sent the response.
     *
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     */
    private $member_id = 0;
    /**
     * revision is the key-value store revision when the request was applied.
     * For watch progress responses, the header.revision indicates progress. All future events
     * recieved in this stream are guaranteed to have a higher revision number than the
     * header.revision number.
     *
     * Generated from protobuf field <code>int64 revision = 3;</code>
     */
    private $revision = 0;
    /**
     * raft_term is the raft term when the request was applied.
     *
     * Generated from protobuf field <code>uint64 raft_term = 4;</code>
     */
    private $raft_term = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $cluster_id
     *           cluster_id is the ID of the cluster which sent the response.
     *     @type int|string $member_id
     *           member_id is the ID of the member which sent the response.
     *     @type int|string $revision
     *           revision is the key-value store revision when the request was applied.
     *           For watch progress responses, the header.revision indicates progress. All future events
     *           recieved in this stream are guaranteed to have a higher revision number than the
     *           header.revision number.
     *     @type int|string $raft_term
     *           raft_term is the raft term when the request was applied.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * cluster_id is the ID of the cluster which sent the response.
     *
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     * @return int|string
     */
    public function getClusterId()
    {
        return $this->cluster_id;
    }

    /**
     * cluster_id is the ID of the cluster which sent the response.
     *
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClusterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->cluster_id = $var;

        return $this;
    }

    /**
     * member_id is the ID of the member which sent the response.
     *
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     * @return int|string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * member_id is the ID of the member which sent the response.
     *
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkUint64($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     * revision is the key-value store revision when the request was applied.
     * For watch progress responses, the header.revision indicates progress. All future events
     * recieved in this stream are guaranteed to have a higher revision number than the
     * header.revision number.
     *
     * Generated from protobuf field <code>int64 revision = 3;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * revision is the key-value store revision when the request was applied.
     * For watch progress responses, the header.revision indicates progress. All future events
     * recieved in this stream are guaranteed to have a higher revision number than the
     * header.revision number.
     *
     * Generated from protobuf field <code>int64 revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * raft_term is the raft term when the request was applied.
     *
     * Generated from protobuf field <code>uint64 raft_term = 4;</code>
     * @return int|string
     */
    public function getRaftTerm()
    {
        return $this->raft_term;
    }

    /**
     * raft_term is the raft term when the request was applied.
     *
     * Generated from protobuf field <code>uint64 raft_term = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRaftTerm($var)
    {
        GPBUtil::checkUint64($var);
        $this->raft_term = $var;

        return $this;
    }

}

