<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.SnapshotResponse</code>
 */
class SnapshotResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * header has the current key-value store information. The first header in the snapshot
     * stream indicates the point in time of the snapshot.
     *
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * remaining_bytes is the number of blob bytes to be sent after this message
     *
     * Generated from protobuf field <code>uint64 remaining_bytes = 2;</code>
     */
    private $remaining_bytes = 0;
    /**
     * blob contains the next chunk of the snapshot in the snapshot stream.
     *
     * Generated from protobuf field <code>bytes blob = 3;</code>
     */
    private $blob = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\ResponseHeader $header
     *           header has the current key-value store information. The first header in the snapshot
     *           stream indicates the point in time of the snapshot.
     *     @type int|string $remaining_bytes
     *           remaining_bytes is the number of blob bytes to be sent after this message
     *     @type string $blob
     *           blob contains the next chunk of the snapshot in the snapshot stream.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * header has the current key-value store information. The first header in the snapshot
     * stream indicates the point in time of the snapshot.
     *
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcdserverpb\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * header has the current key-value store information. The first header in the snapshot
     * stream indicates the point in time of the snapshot.
     *
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcdserverpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * remaining_bytes is the number of blob bytes to be sent after this message
     *
     * Generated from protobuf field <code>uint64 remaining_bytes = 2;</code>
     * @return int|string
     */
    public function getRemainingBytes()
    {
        return $this->remaining_bytes;
    }

    /**
     * remaining_bytes is the number of blob bytes to be sent after this message
     *
     * Generated from protobuf field <code>uint64 remaining_bytes = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRemainingBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->remaining_bytes = $var;

        return $this;
    }

    /**
     * blob contains the next chunk of the snapshot in the snapshot stream.
     *
     * Generated from protobuf field <code>bytes blob = 3;</code>
     * @return string
     */
    public function getBlob()
    {
        return $this->blob;
    }

    /**
     * blob contains the next chunk of the snapshot in the snapshot stream.
     *
     * Generated from protobuf field <code>bytes blob = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBlob($var)
    {
        GPBUtil::checkString($var, False);
        $this->blob = $var;

        return $this;
    }

}

