<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.TxnResponse</code>
 */
class TxnResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     *
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     */
    private $succeeded = false;
    /**
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     */
    private $responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\ResponseHeader $header
     *     @type bool $succeeded
     *           succeeded is set to true if the compare evaluated to true or false otherwise.
     *     @type \Etcdserverpb\ResponseOp[]|\Google\Protobuf\Internal\RepeatedField $responses
     *           responses is a list of responses corresponding to the results from applying
     *           success if succeeded is true or failure if succeeded is false.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcdserverpb\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcdserverpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     *
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     * @return bool
     */
    public function getSucceeded()
    {
        return $this->succeeded;
    }

    /**
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     *
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSucceeded($var)
    {
        GPBUtil::checkBool($var);
        $this->succeeded = $var;

        return $this;
    }

    /**
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     *
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     * @param \Etcdserverpb\ResponseOp[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcdserverpb\ResponseOp::class);
        $this->responses = $arr;

        return $this;
    }

}

