<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

if (false) {
    /**
     * This class is deprecated. Use Etcdserverpb\WatchCreateRequest\FilterType instead.
     * @deprecated
     */
    class WatchCreateRequest_FilterType {}
}
class_exists(WatchCreateRequest\FilterType::class);
@trigger_error('Etcdserverpb\WatchCreateRequest_FilterType is deprecated and will be removed in the next major release. Use Etcdserverpb\WatchCreateRequest\FilterType instead', E_USER_DEPRECATED);

