<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.WatchRequest</code>
 */
class WatchRequest extends \Google\Protobuf\Internal\Message
{
    protected $request_union;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcdserverpb\WatchCreateRequest $create_request
     *     @type \Etcdserverpb\WatchCancelRequest $cancel_request
     *     @type \Etcdserverpb\WatchProgressRequest $progress_request
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
     * @return \Etcdserverpb\WatchCreateRequest
     */
    public function getCreateRequest()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
     * @param \Etcdserverpb\WatchCreateRequest $var
     * @return $this
     */
    public function setCreateRequest($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\WatchCreateRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
     * @return \Etcdserverpb\WatchCancelRequest
     */
    public function getCancelRequest()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
     * @param \Etcdserverpb\WatchCancelRequest $var
     * @return $this
     */
    public function setCancelRequest($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\WatchCancelRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.WatchProgressRequest progress_request = 3;</code>
     * @return \Etcdserverpb\WatchProgressRequest
     */
    public function getProgressRequest()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.WatchProgressRequest progress_request = 3;</code>
     * @param \Etcdserverpb\WatchProgressRequest $var
     * @return $this
     */
    public function setProgressRequest($var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\WatchProgressRequest::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequestUnion()
    {
        return $this->whichOneof("request_union");
    }

}

