<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Authpb;

if (false) {
    /**
     * This class is deprecated. Use Authpb\Permission\Type instead.
     * @deprecated
     */
    class Permission_Type {}
}
class_exists(Permission\Type::class);
@trigger_error('Authpb\Permission_Type is deprecated and will be removed in the next major release. Use Authpb\Permission\Type instead', E_USER_DEPRECATED);

