<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Authpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Permission is a single entity
 *
 * Generated from protobuf message <code>authpb.Permission</code>
 */
class Permission extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authpb.Permission.Type permType = 1;</code>
     */
    private $permType = 0;
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>bytes range_end = 3;</code>
     */
    private $range_end = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $permType
     *     @type string $key
     *     @type string $range_end
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authpb.Permission.Type permType = 1;</code>
     * @return int
     */
    public function getPermType()
    {
        return $this->permType;
    }

    /**
     * Generated from protobuf field <code>.authpb.Permission.Type permType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPermType($var)
    {
        GPBUtil::checkEnum($var, \Authpb\Permission_Type::class);
        $this->permType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes range_end = 3;</code>
     * @return string
     */
    public function getRangeEnd()
    {
        return $this->range_end;
    }

    /**
     * Generated from protobuf field <code>bytes range_end = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRangeEnd($var)
    {
        GPBUtil::checkString($var, False);
        $this->range_end = $var;

        return $this;
    }

}

