<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb\AlarmRequest;

/**
 * Protobuf type <code>etcdserverpb.AlarmRequest.AlarmAction</code>
 */
class AlarmAction
{
    /**
     * Generated from protobuf enum <code>GET = 0;</code>
     */
    const GET = 0;
    /**
     * Generated from protobuf enum <code>ACTIVATE = 1;</code>
     */
    const ACTIVATE = 1;
    /**
     * Generated from protobuf enum <code>DEACTIVATE = 2;</code>
     */
    const DEACTIVATE = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AlarmAction::class, \Etcdserverpb\AlarmRequest_AlarmAction::class);

